<footer>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="art.html">Art</a></li>
					<li><a href="location.html">Location</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
			<div class="copyright">
				<p>Copyright Lucas Rasmussen 2013, For educational purposes only at this time.</p>
			</div>
			
		</footer>