		<header>
			<nav>
				<div>
					<ul class="left-nav">
						<li><a href="#">About</a></li>
						<li><a href="#">Art</a></li>
					</ul>
					<div class="center"><a href="#"><img type="image/svg+xml" src="./images/aarhus-header.svg"></img></a></div>
					<ul class="right-nav">
						<li ><a href="#">Location</a></li>
						<li ><a href="#">Contact</a></li>
					</ul>
				</div>
			</nav>
		</header>
