		<header>
			<nav>
				<div>
					<ul class="left-nav">
						<li><a href="about.html">About</a></li>
						<li><a href="art.html">Art</a></li>
					</ul>
					<div class="center"><a href="index.html"><img type="image/svg+xml" src="./images/aarhus-header.svg" title="home" alt="welcome to Aarhus logo"></img></a></div>
					<ul class="right-nav">
						<li ><a href="location.html">Location</a></li>
						<li ><a href="contact.html">Contact</a></li>
					</ul>
				</div>
			</nav>
		</header>
