	<head>
		<title>Aarhus Denmark</title>
		<meta charset="utf-8"></meta>
		<link href="http://www.visitaarhus.dk/sites/all/themes/visit/favicon.ico" rel="shortcut icon"></link>
		<script type="text/javascript" src="//use.typekit.net/bnx5qwk.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
		<link href="stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
		
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
	</head>